// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eDom.Infrastructure.Data;

#nullable disable

namespace eDom.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HctDbContext))]
    [Migration("20260427163833_RemoveFunzioneShadowNavigations")]
    partial class RemoveFunzioneShadowNavigations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("HICT")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SI_UTENRUOL", b =>
                {
                    b.Property<int>("UTRU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UTRU_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UTRU_ID"));

                    b.Property<int?>("UTRU_PROC_ID")
                        .HasColumnType("integer")
                        .HasColumnName("UTRU_PROC_ID");

                    b.Property<int>("UTRU_RUOL_ID")
                        .HasColumnType("integer")
                        .HasColumnName("UTRU_RUOL_ID");

                    b.Property<int>("UTRU_UTEN_ID")
                        .HasColumnType("integer")
                        .HasColumnName("UTRU_UTEN_ID");

                    b.HasKey("UTRU_ID");

                    b.HasIndex("UTRU_RUOL_ID");

                    b.HasIndex("UTRU_UTEN_ID");

                    b.ToTable("SI_UTENRUOL", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("AULO_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataOperazione")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AULO_DTOP");

                    b.Property<string>("EntitaId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("AULO_ENTITA_ID");

                    b.Property<string>("Operazione")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("AULO_OPERAZIONE");

                    b.Property<string>("Tabella")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("AULO_TABELLA");

                    b.Property<int?>("UtenteId")
                        .HasColumnType("integer")
                        .HasColumnName("AULO_UTEN_ID");

                    b.Property<string>("ValoriNuovi")
                        .HasColumnType("text")
                        .HasColumnName("AULO_NEW_VALUES");

                    b.Property<string>("ValoriPrecedenti")
                        .HasColumnType("text")
                        .HasColumnName("AULO_OLD_VALUES");

                    b.HasKey("Id");

                    b.ToTable("SI_AUDIT_LOG", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.Configurazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CONF_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CONF_CODICE");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CONF_DESCR");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("CONF_PROC_ID");

                    b.Property<string>("Valore")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CONF_VALORE");

                    b.HasKey("Id");

                    b.ToTable("SI_CONFIG", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.Funzione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FUNZ_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FUNZ_CODICE");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FUNZ_DTINS");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FUNZ_DTMOD");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("FUNZ_DESCR");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("FUNZ_PARENT");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("FUNZ_PROC_ID");

                    b.Property<string>("Sort")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FUNZ_SORT");

                    b.Property<int>("UtenteInserimento")
                        .HasColumnType("integer")
                        .HasColumnName("FUNZ_UTINS");

                    b.Property<int?>("UtenteModifica")
                        .HasColumnType("integer")
                        .HasColumnName("FUNZ_UTMOD");

                    b.Property<DateTime?>("Version")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FUNZ_VERSION");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("SI_FUNZIONI", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.LogAccesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("LOAC_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LOAC_DATE");

                    b.Property<int>("FunzioneId")
                        .HasColumnType("integer")
                        .HasColumnName("LOAC_FUNZ_ID");

                    b.Property<string>("IndirizzoIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LOAC_IPADDR");

                    b.Property<string>("NomeMacchina")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("LOAC_MACHINE");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("LOAC_PROC_ID");

                    b.Property<int>("UtenteId")
                        .HasColumnType("integer")
                        .HasColumnName("LOAC_UTEN_ID");

                    b.HasKey("Id");

                    b.ToTable("SI_LOGACC", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.Paziente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaDomicilioId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_AREADOM_ID");

                    b.Property<int?>("AreaRepartoId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_AREAREP_ID");

                    b.Property<int>("AreaResidenzaId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_AREARES_ID");

                    b.Property<short>("Attivo")
                        .HasColumnType("smallint")
                        .HasColumnName("PAZI_F_ATT");

                    b.Property<string>("CameraReparto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PAZI_CAMPREP");

                    b.Property<string>("CapDomicilio")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("PAZI_CAPDOM");

                    b.Property<string>("CapReparto")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("PAZI_CAPREP");

                    b.Property<string>("CapResidenza")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("PAZI_CAPRES");

                    b.Property<int>("CittadinanzaId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_CITTADIN_ID");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PAZI_CODICE");

                    b.Property<string>("CodiceAlternativo1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PAZI_CODALT01");

                    b.Property<string>("CodiceAlternativo2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PAZI_CODALT02");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PAZI_CODFISC");

                    b.Property<string>("CodiceFiscaleFam1")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PAZI_CODFISCFAM1");

                    b.Property<string>("CodiceFiscaleMadre")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PAZI_CODFISCMADRE");

                    b.Property<string>("CodiceFiscalePadre")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("PAZI_CODFISCPADRE");

                    b.Property<string>("CodiceSanitario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PAZI_CODICESANIT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAZI_COGNOME");

                    b.Property<string>("CognomeFam1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAZI_COGNOMEFAM1");

                    b.Property<string>("CognomeMadre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAZI_COGNOMEMADRE");

                    b.Property<string>("CognomePadre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAZI_COGNOMEPADRE");

                    b.Property<int?>("ComuneDomicilioId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_COMDOM_ID");

                    b.Property<int>("ComuneNascitaId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_COMNAS_ID");

                    b.Property<int?>("ComuneRepartoId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_COMREP_ID");

                    b.Property<int?>("ComuneResidenzaFam1Id")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_COMRESFAM1_ID");

                    b.Property<int>("ComuneResidenzaId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_COMRES_ID");

                    b.Property<int?>("ComuneResidenzaMadreId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_COMRESMADRE_ID");

                    b.Property<int?>("ComuneResidenzaPadreId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_COMRESPADRE_ID");

                    b.Property<int?>("CondizioneProfId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ELTG_CONDPROFES");

                    b.Property<int?>("ConsultorioId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_CONSULTORIO_ID");

                    b.Property<DateTime?>("DataEsenzione")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_DTESENZ");

                    b.Property<DateTime?>("DataEventoAnagrafe")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_DTEVEANAG");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_DTINS");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_DTMOD");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_DTNAS");

                    b.Property<DateTime?>("DataNascitaFam1")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_DTNASFAM1");

                    b.Property<DateTime?>("DataNascitaMadre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_DTNASMADRE");

                    b.Property<DateTime?>("DataNascitaPadre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_DTNASPADRE");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PAZI_EMAIL");

                    b.Property<int?>("EsenzioneId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ESENZ_ID");

                    b.Property<int?>("EventoAnagrafId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ELTG_EVEANAG");

                    b.Property<string>("IndirizzoDomicilio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PAZI_INDDOM");

                    b.Property<string>("IndirizzoFam1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PAZI_INDRESFAM1");

                    b.Property<string>("IndirizzoMadre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PAZI_INDRESMADRE");

                    b.Property<string>("IndirizzoPadre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PAZI_INDRESPADRE");

                    b.Property<string>("IndirizzoReparto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PAZI_INDREP");

                    b.Property<string>("IndirizzoResidenza")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PAZI_INDRES");

                    b.Property<int?>("MedicoId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_MEDICO_ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAZI_NOME");

                    b.Property<string>("NomeFam1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAZI_NOMEFAM1");

                    b.Property<string>("NomeMadre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAZI_NOMEMADRE");

                    b.Property<string>("NomePadre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PAZI_NOMEPADRE");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("PAZI_NOTE01");

                    b.Property<string>("NumeroDocumentoStraniero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PAZI_STRANDOCNUM");

                    b.Property<string>("NumeroTeamEuropeo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PAZI_TEAMNUM");

                    b.Property<int?>("PosizioneProfId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ELTG_POSPROFES");

                    b.Property<int?>("ProfessioneId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ELTG_PROFES");

                    b.Property<int?>("ReligioneId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ELTG_RELIG");

                    b.Property<DateTime?>("ScadenzaDocumentoStraniero")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_STRANDOCSCAD");

                    b.Property<DateTime?>("ScadenzaTeamEuropeo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_TEAMSCAD");

                    b.Property<string>("Sesso")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("PAZI_SESSO");

                    b.Property<int>("StatoCivileId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ELTG_STATOCIV");

                    b.Property<string>("Telefono1")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PAZI_TELEF01");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PAZI_TELEF02");

                    b.Property<string>("Telefono3")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PAZI_TELEF03");

                    b.Property<string>("TelefonoFam1")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PAZI_TELEFFAM1");

                    b.Property<string>("TelefonoMadre")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PAZI_TELEFMADRE");

                    b.Property<string>("TelefonoPadre")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("PAZI_TELEFPADRE");

                    b.Property<int?>("TipoDocumentoStranieroId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ELTG_STRANDOCTIPO");

                    b.Property<int?>("TitoloStudioId")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_ELTG_TITSTU");

                    b.Property<int>("UtenteInserimento")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_UTINS");

                    b.Property<int?>("UtenteModifica")
                        .HasColumnType("integer")
                        .HasColumnName("PAZI_UTMOD");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_VALID_FROM");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_VALID_TO");

                    b.Property<DateTime?>("Version")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PAZI_VERSION");

                    b.HasKey("Id");

                    b.ToTable("CO_PAZIENTI", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.Procedura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PROC_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("PROC_CODICE");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PROC_DTINS");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PROC_DTMOD");

                    b.Property<string>("DbPassword")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PROC_DBPWD");

                    b.Property<string>("DbSchema")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PROC_DBSCHEMA");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PROC_DESCR");

                    b.Property<int>("UtenteInserimento")
                        .HasColumnType("integer")
                        .HasColumnName("PROC_UTINS");

                    b.Property<int?>("UtenteModifica")
                        .HasColumnType("integer")
                        .HasColumnName("PROC_UTMOD");

                    b.Property<DateTime?>("Version")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PROC_VERSION");

                    b.Property<short>("Visibile")
                        .HasColumnType("smallint")
                        .HasColumnName("PROC_VISIBILE");

                    b.HasKey("Id");

                    b.ToTable("SI_PROCEDURE", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.Ruolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RUOL_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("RUOL_CODICE");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RUOL_DTINS");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RUOL_DTMOD");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("RUOL_DESCR");

                    b.Property<short>("FlagAdmin")
                        .HasColumnType("smallint")
                        .HasColumnName("RUOL_F_ADMIN");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("RUOL_PROC_ID");

                    b.Property<int>("UtenteInserimento")
                        .HasColumnType("integer")
                        .HasColumnName("RUOL_UTINS");

                    b.Property<int?>("UtenteModifica")
                        .HasColumnType("integer")
                        .HasColumnName("RUOL_UTMOD");

                    b.Property<DateTime?>("Version")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RUOL_VERSION");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureId");

                    b.ToTable("SI_RUOLI", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.RuoloFunzione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RUFU_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RUFU_DTINS");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RUFU_DTMOD");

                    b.Property<int>("FunzioneId")
                        .HasColumnType("integer")
                        .HasColumnName("RUFU_FUNZ_ID");

                    b.Property<int>("FunzioneProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("RUFU_FUNZ_PROC_ID");

                    b.Property<int>("RuoloId")
                        .HasColumnType("integer")
                        .HasColumnName("RUFU_RUOL_ID");

                    b.Property<int>("RuoloProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("RUFU_RUOL_PROC_ID");

                    b.Property<int>("UtenteInserimento")
                        .HasColumnType("integer")
                        .HasColumnName("RUFU_UTINS");

                    b.Property<int?>("UtenteModifica")
                        .HasColumnType("integer")
                        .HasColumnName("RUFU_UTMOD");

                    b.Property<DateTime?>("Version")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RUFU_VERSION");

                    b.HasKey("Id");

                    b.HasIndex("FunzioneId");

                    b.HasIndex("FunzioneProcedureId");

                    b.HasIndex("RuoloId");

                    b.HasIndex("RuoloProcedureId");

                    b.ToTable("SI_RUOLFUNZ", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.UserDashboardLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DASH_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DASH_LAYOUT_JSON");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DASH_UPDATED_AT");

                    b.Property<string>("UserCodice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DASH_USER_CODICE");

                    b.HasKey("Id");

                    b.HasIndex("UserCodice")
                        .IsUnique()
                        .HasDatabaseName("UX_DASH_USER_CODICE");

                    b.ToTable("APP_DASH_LAYOUT", "HICT");
                });

            modelBuilder.Entity("eDom.Core.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UTEN_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UTEN_CODICE");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("UTEN_CODFISC");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("UTEN_COGNOME");

                    b.Property<DateTime?>("DataDisattivazione")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTEN_DTDISAT");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTEN_DTINS");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTEN_DTMOD");

                    b.Property<DateTime?>("DataRiattivazione")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTEN_DTRIAT");

                    b.Property<DateTime?>("DataScadenzaPassword")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTEN_DTSCPASS");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("UTEN_EMAIL");

                    b.Property<short>("FlagCambiaPwd")
                        .HasColumnType("smallint")
                        .HasColumnName("UTEN_F_CHPASS");

                    b.Property<short>("FlagSmartCard")
                        .HasColumnType("smallint")
                        .HasColumnName("UTEN_F_SMCARD");

                    b.Property<string>("Matricola")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UTEN_MATR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("UTEN_NOME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("UTEN_PASSWD");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTEN_LASTLOGIN");

                    b.Property<int>("UtenteInserimento")
                        .HasColumnType("integer")
                        .HasColumnName("UTEN_UTINS");

                    b.Property<int?>("UtenteModifica")
                        .HasColumnType("integer")
                        .HasColumnName("UTEN_UTMOD");

                    b.Property<DateTime?>("Version")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UTEN_VERSION");

                    b.HasKey("Id");

                    b.ToTable("SI_UTENTI", "HICT");
                });

            modelBuilder.Entity("SI_UTENRUOL", b =>
                {
                    b.HasOne("eDom.Core.Entities.Ruolo", null)
                        .WithMany()
                        .HasForeignKey("UTRU_RUOL_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eDom.Core.Entities.Utente", null)
                        .WithMany()
                        .HasForeignKey("UTRU_UTEN_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eDom.Core.Entities.Funzione", b =>
                {
                    b.HasOne("eDom.Core.Entities.Funzione", "Padre")
                        .WithMany("Figlie")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("eDom.Core.Entities.Procedura", "Procedura")
                        .WithMany("Funzioni")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Padre");

                    b.Navigation("Procedura");
                });

            modelBuilder.Entity("eDom.Core.Entities.Ruolo", b =>
                {
                    b.HasOne("eDom.Core.Entities.Procedura", null)
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("eDom.Core.Entities.RuoloFunzione", b =>
                {
                    b.HasOne("eDom.Core.Entities.Funzione", "Funzione")
                        .WithMany("RuoliFunzione")
                        .HasForeignKey("FunzioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eDom.Core.Entities.Procedura", "FunzioneProcedura")
                        .WithMany()
                        .HasForeignKey("FunzioneProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eDom.Core.Entities.Ruolo", "Ruolo")
                        .WithMany()
                        .HasForeignKey("RuoloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eDom.Core.Entities.Procedura", "RuoloProcedura")
                        .WithMany()
                        .HasForeignKey("RuoloProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funzione");

                    b.Navigation("FunzioneProcedura");

                    b.Navigation("Ruolo");

                    b.Navigation("RuoloProcedura");
                });

            modelBuilder.Entity("eDom.Core.Entities.Funzione", b =>
                {
                    b.Navigation("Figlie");

                    b.Navigation("RuoliFunzione");
                });

            modelBuilder.Entity("eDom.Core.Entities.Procedura", b =>
                {
                    b.Navigation("Funzioni");
                });
#pragma warning restore 612, 618
        }
    }
}
