using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace eDom.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class ApplyLatestModelChanges : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                DECLARE
                    seq_name text;
                    max_id bigint;
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT'
                          AND table_name = 'SI_RUOLI'
                          AND column_name = 'RUOL_ID'
                          AND identity_generation IS NOT NULL
                    ) THEN
                        ALTER TABLE "HICT"."SI_RUOLI"
                            ALTER COLUMN "RUOL_ID" DROP DEFAULT;

                        ALTER TABLE "HICT"."SI_RUOLI"
                            ALTER COLUMN "RUOL_ID" ADD GENERATED BY DEFAULT AS IDENTITY;
                    END IF;

                    SELECT pg_get_serial_sequence('"HICT"."SI_RUOLI"', 'RUOL_ID') INTO seq_name;
                    EXECUTE 'SELECT COALESCE(MAX("RUOL_ID"), 0) FROM "HICT"."SI_RUOLI"' INTO max_id;

                    IF seq_name IS NOT NULL THEN
                        IF max_id <= 0 THEN
                            EXECUTE format('SELECT setval(%L, 1, false)', seq_name);
                        ELSE
                            EXECUTE format('SELECT setval(%L, %s, true)', seq_name, max_id);
                        END IF;
                    END IF;
                END $$;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // No-op: this migration enforces identity semantics and realigns its counter.
        }
    }
}
