using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace eDom.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class AlignSiUtenruolMapping : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    ALTER TABLE "HICT"."SI_UTENRUOL" DROP CONSTRAINT IF EXISTS "FK_SI_UTENRUOL_SI_RUOLI_RuoliId";
                    ALTER TABLE "HICT"."SI_UTENRUOL" DROP CONSTRAINT IF EXISTS "FK_SI_UTENRUOL_SI_UTENTI_UtentiId";
                    ALTER TABLE "HICT"."SI_UTENRUOL" DROP CONSTRAINT IF EXISTS "FK_SI_UTENRUOL_SI_RUOLI_UTRU_RUOL_ID";
                    ALTER TABLE "HICT"."SI_UTENRUOL" DROP CONSTRAINT IF EXISTS "FK_SI_UTENRUOL_SI_UTENTI_UTRU_UTEN_ID";
                    ALTER TABLE "HICT"."SI_UTENRUOL" DROP CONSTRAINT IF EXISTS "PK_SI_UTENRUOL";

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'UtentiId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'UTRU_UTEN_ID'
                    ) THEN
                        ALTER TABLE "HICT"."SI_UTENRUOL" RENAME COLUMN "UtentiId" TO "UTRU_UTEN_ID";
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'RuoliId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'UTRU_RUOL_ID'
                    ) THEN
                        ALTER TABLE "HICT"."SI_UTENRUOL" RENAME COLUMN "RuoliId" TO "UTRU_RUOL_ID";
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM pg_class i
                        JOIN pg_namespace n ON n.oid = i.relnamespace
                        WHERE n.nspname = 'HICT' AND i.relname = 'IX_SI_UTENRUOL_UtentiId'
                    ) AND NOT EXISTS (
                        SELECT 1
                        FROM pg_class i
                        JOIN pg_namespace n ON n.oid = i.relnamespace
                        WHERE n.nspname = 'HICT' AND i.relname = 'IX_SI_UTENRUOL_UTRU_UTEN_ID'
                    ) THEN
                        ALTER INDEX "HICT"."IX_SI_UTENRUOL_UtentiId" RENAME TO "IX_SI_UTENRUOL_UTRU_UTEN_ID";
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'UTRU_ID'
                    ) THEN
                        ALTER TABLE "HICT"."SI_UTENRUOL"
                        ADD COLUMN "UTRU_ID" integer GENERATED BY DEFAULT AS IDENTITY;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'UTRU_PROC_ID'
                    ) THEN
                        ALTER TABLE "HICT"."SI_UTENRUOL" ADD COLUMN "UTRU_PROC_ID" integer NULL;
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'UTRU_UTEN_ID' AND udt_name <> 'int4'
                    ) THEN
                        ALTER TABLE "HICT"."SI_UTENRUOL"
                        ALTER COLUMN "UTRU_UTEN_ID" TYPE integer USING "UTRU_UTEN_ID"::integer;
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'UTRU_RUOL_ID' AND udt_name <> 'int4'
                    ) THEN
                        ALTER TABLE "HICT"."SI_UTENRUOL"
                        ALTER COLUMN "UTRU_RUOL_ID" TYPE integer USING "UTRU_RUOL_ID"::integer;
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'HICT' AND table_name = 'SI_UTENRUOL' AND column_name = 'UTRU_ID' AND udt_name <> 'int4'
                    ) THEN
                        ALTER TABLE "HICT"."SI_UTENRUOL"
                        ALTER COLUMN "UTRU_ID" TYPE integer USING "UTRU_ID"::integer;
                    END IF;
                END $$;
                """);

            migrationBuilder.Sql(
                "ALTER TABLE \"HICT\".\"SI_UTENRUOL\" ADD CONSTRAINT \"PK_SI_UTENRUOL\" PRIMARY KEY (\"UTRU_ID\");");

            migrationBuilder.Sql(
                "CREATE INDEX IF NOT EXISTS \"IX_SI_UTENRUOL_UTRU_RUOL_ID\" ON \"HICT\".\"SI_UTENRUOL\" (\"UTRU_RUOL_ID\");");

            migrationBuilder.Sql(
                "ALTER TABLE \"HICT\".\"SI_UTENRUOL\" ADD CONSTRAINT \"FK_SI_UTENRUOL_SI_RUOLI_UTRU_RUOL_ID\" FOREIGN KEY (\"UTRU_RUOL_ID\") REFERENCES \"HICT\".\"SI_RUOLI\" (\"RUOL_ID\") ON DELETE CASCADE;");

            migrationBuilder.Sql(
                "ALTER TABLE \"HICT\".\"SI_UTENRUOL\" ADD CONSTRAINT \"FK_SI_UTENRUOL_SI_UTENTI_UTRU_UTEN_ID\" FOREIGN KEY (\"UTRU_UTEN_ID\") REFERENCES \"HICT\".\"SI_UTENTI\" (\"UTEN_ID\") ON DELETE CASCADE;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_SI_UTENRUOL_SI_RUOLI_UTRU_RUOL_ID",
                schema: "HICT",
                table: "SI_UTENRUOL");

            migrationBuilder.DropForeignKey(
                name: "FK_SI_UTENRUOL_SI_UTENTI_UTRU_UTEN_ID",
                schema: "HICT",
                table: "SI_UTENRUOL");

            migrationBuilder.DropPrimaryKey(
                name: "PK_SI_UTENRUOL",
                schema: "HICT",
                table: "SI_UTENRUOL");

            migrationBuilder.DropIndex(
                name: "IX_SI_UTENRUOL_UTRU_RUOL_ID",
                schema: "HICT",
                table: "SI_UTENRUOL");

            migrationBuilder.DropColumn(
                name: "UTRU_ID",
                schema: "HICT",
                table: "SI_UTENRUOL");

            migrationBuilder.DropColumn(
                name: "UTRU_PROC_ID",
                schema: "HICT",
                table: "SI_UTENRUOL");

            migrationBuilder.RenameColumn(
                name: "UTRU_UTEN_ID",
                schema: "HICT",
                table: "SI_UTENRUOL",
                newName: "UtentiId");

            migrationBuilder.RenameColumn(
                name: "UTRU_RUOL_ID",
                schema: "HICT",
                table: "SI_UTENRUOL",
                newName: "RuoliId");

            migrationBuilder.RenameIndex(
                name: "IX_SI_UTENRUOL_UTRU_UTEN_ID",
                schema: "HICT",
                table: "SI_UTENRUOL",
                newName: "IX_SI_UTENRUOL_UtentiId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_SI_UTENRUOL",
                schema: "HICT",
                table: "SI_UTENRUOL",
                columns: new[] { "RuoliId", "UtentiId" });

            migrationBuilder.AddForeignKey(
                name: "FK_SI_UTENRUOL_SI_RUOLI_RuoliId",
                schema: "HICT",
                table: "SI_UTENRUOL",
                column: "RuoliId",
                principalSchema: "HICT",
                principalTable: "SI_RUOLI",
                principalColumn: "RUOL_ID",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_SI_UTENRUOL_SI_UTENTI_UtentiId",
                schema: "HICT",
                table: "SI_UTENRUOL",
                column: "UtentiId",
                principalSchema: "HICT",
                principalTable: "SI_UTENTI",
                principalColumn: "UTEN_ID",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
